spring:
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.mailgun.org
    username: mailgunlogin@sandboxc4c707dd5769438191a154d8220fe1ff.mailgun.org

jwt:
  expiration-minutes: 1000

nginx:
  require-proxy: false

chirp:
  email:
    url: "http://localhost:8080"
  rate-limit:
    ip:
      apply-limit: true
  web-socket:
    allowed-origin: "http://localhost:8080"