spring:
  jpa:
    hibernate:
      ddl-auto: validate
  mail:
    host: smtp.mailgun.org
    username: mailgunlogin@sandboxc4c707dd5769438191a154d8220fe1ff.mailgun.org
jwt:
  expiration-minutes: 15

nginx:
  require-proxy: true

chirp:
  rate-limit:
    ip:
      apply-limit: false